# -*- coding: utf-8 -*-
"""Resume_Candidate_Screening_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQpeSns7pKMAliqgZeMUbC2PgQnCJQr8
"""

!pip install kaggle
!pip install nltk
!pip install scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

nltk.download('punkt')
nltk.download('stopwords')

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp *.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list -s "resume screening"

!kaggle datasets download -d serkanp/resume-screening-dataset

!unzip resume-screening-dataset.zip

!ls

import pandas as pd

df = pd.read_csv("Resume Screening.csv")

df.head()

df.info()

df.isnull().sum()

df.columns

X = df["Resume"]
y = df["Category"]

print(X.isnull().sum())
print(y.isnull().sum())

df = df.dropna(subset=["Resume", "Category"])

X = df["Resume"]
y = df["Category"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

disp.plot(cmap="Blues", xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(10,5))

df["Category"].value_counts().plot(kind="bar")

plt.title("Resume Category Distribution")
plt.xlabel("Category")
plt.ylabel("Count")
plt.show()

sample_resume = ["""
Python, Machine Learning, Data Analysis,
Pandas, NumPy, Scikit-learn,
SQL, Deep Learning, TensorFlow
"""]

sample_vector = vectorizer.transform(sample_resume)

prediction = model.predict(sample_vector)

print("Predicted Category:", prediction[0])

"""## Business Insights

- The system automatically classifies resumes into relevant categories.
- Resume screening reduces manual effort in recruitment.
- Automated classification speeds up candidate shortlisting.
- Recruiters can quickly identify suitable candidates for different job roles.

## Conclusion

A Resume Screening System was developed using Natural Language Processing (NLP) and Logistic Regression. The model successfully classifies resumes into different categories based on resume content, helping recruiters automate candidate screening and improve hiring efficiency.
"""